services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
      # Environment variables has to be passed at build time with Vite.
      args:
        - PORT=${FC_PORT}
        - FH_URL=${FH_URL}
        - FH_PORT=${FH_PORT}
        - FC_PORT=${FC_PORT}
        - BH_URL=${FH_URL}
        - BH_PORT=${BH_PORT}
    ports:
      - ${FH_PORT}:${FC_PORT} # access frontend on port 3000
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
      args:
        - PORT=${BC_PORT}
    environment:
      - BH_PORT=${BH_PORT}
      - FH_URL=${FH_URL}
      - FH_PORT=${FH_PORT}
    ports:
      - "${BH_PORT}:${BC_PORT}"
